### ISSUE TITLE
ユーザ(寺院側)登録まわり

### ISSUE THREAD

**Issue by oratake** [oratake/zenji-laravel#1]
# 概要
ユーザ(寺院側)登録を作りたい。

# やりたいこと
- ユーザ登録
- ログイン関係

## テーブル案

|カラム名|column_name|備考|
|:---|:---|:---|
|uuid|id|キーid|
|登録メールアドレス|mail||
|パスワード|password||
|僧名|user_name|利用者名|
|寺院名|jiin_name|所属する寺院の名称|

- 寺院名は後で別テーブルにするなど考えたいが、一旦はstringにする
  - 寺院ごとのユーザ登録にするか?とも思うが、ひとまず一人一人登録にしたい
- ログイン関係はなるべくLaravelの機能を使い倒すほうに行きたい
  - TechpitだとVueのようなSPAアプリになるのでそれ向きの機能を使っているか?Laravel Sanctumなど

**Comment by Osatsu025** [comment]
型とかこんな感じ…？

カラム名 | column_name | 備考 | 型や制約
-- | -- | -- | --
uuid | id | キーid | increments
登録メールアドレス | mail | | string, unique
パスワード | password_hash | | string
僧名 | user_name | 利用者名 | string
寺院名 | jiin_name | 所属する寺院の名称 | string

**Comment by oratake** [comment]
バスワードのカラム名、LaravelのAuthトレイトの初期設定に合わせて `password_hash` → `password` に

**Comment by Osatsu025** [comment]
カラム名 | column_name | 備考 | 型や制約
-- | -- | -- | --
uuid | id | キーid | increments
登録メールアドレス | mail |   | string, unique
パスワード | password |   | string
僧名 | user_name | 利用者名 | string
寺院名 | jiin_name | 所属する寺院の名称 | string

**Comment by Osatsu025** [comment]
カラム名 | column_name | 備考 | 型や制約
-- | -- | -- | --
uuid | id | キーid | id
登録メールアドレス | mail |   | string, unique
パスワード | password |   | string
僧名 | name | 利用者名 | string
寺院名 | jiin_name | 所属する寺院の名称 | string

nameは表示用(ex.「一休」)。バリデーションに```'alpha_num'```入れなければマルチバイト可。
認証はemailとpasswordで行う。

基本はデフォルトのままで、jiin_nameだけマイグレーションで追加する。

**Comment by oratake** [comment]
忘れてたけどmergeしたのでissueも閉じる
#3 Close

**Comment by oratake** [comment]
忘れてたけど #3 のPRをmergeしたのでこのIssueも閉じる
